In [1]:
import pandas as pd
pd.set_option('display.max_columns',200)
pd.set_option('display.max_rows',100)
import numpy as np
import math
import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
%matplotlib inline

In [2]:
def print_full(x):
    pd.set_option('display.max_rows',len(x))
    print(x)
    pd.reset_option('display.max_rows')

In [3]:
data_loc = 'D:\\job_hunting\\blend'
 
df = pd.read_csv(data_loc +'\\'+ 'LoanStats3d.csv')

C:\Users\Chao Cheng\Anaconda2\lib\site-packages\IPython\core\interactiveshell.py:2717: DtypeWarning: Columns (19,55) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

## Is Lending Club making money with the loans in the dataset?

### Let's first look at Lending Club business model:
#### Revenue = Origination Fee  + Service Fee 
##### As long as Lending club would attract personal investor and borrower to get the loan funded, they're making money
[business model](http://vator.tv/news/2014-03-21-how-does-lending-club-make-money#yss2rMyUWuVUhgqZ.99)

[origination fee rate](http://www.lendingmemo.com/rates-fees-lending-club-prosper/)
##### Question becomes how much money they're making based on this dataset?

[business model](http://vator.tv/news/2014-03-21-how-does-lending-club-make-money#yss2rMyUWuVUhgqZ.99)

[origination fee rate](http://www.lendingmemo.com/rates-fees-lending-club-prosper/)

In [15]:
df.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
0,68615169,73517949,16000,16000,16000.0,60 months,8.49%,328.19,B,B1,Supervisor,5 years,MORTGAGE,62000.0,Source Verified,Dec-2015,Current,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,credit_card,Credit card refinancing,936xx,CA,28.92,0,Mar-2002,0,39.0,NaN,10,0,15763,51.2%,24,w,13083.35,13083.35,4247.60,4247.60,2916.65,1330.95,0.0,0.0,0.0,Feb-2017,328.19,Mar-2017,Feb-2017,0,61.0,1,INDIVIDUAL,NaN,NaN,NaN,0,0,227708,3.0,3.0,1.0,2.0,3.0,48608.0,82.0,2.0,4.0,4727.0,71.0,30800,1.0,1.0,0.0,6,22771,8703.0,63.0,0,0,165.0,159,3,3,3,3.0,NaN,17.0,39.0,1,4,5,4,7,9,6,12.0,6,10,0.0,0,0,3,87.5,50.0,0,0,307343,64371,23500,59526
1,68537564,73427399,8000,8000,8000.0,36 months,10.78%,261.08,B,B4,Counselor,< 1 year,MORTGAGE,45000.0,Not Verified,Dec-2015,Current,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,482xx,MI,21.23,0,Jan-1998,0,34.0,NaN,28,0,11141,35.5%,69,w,5403.18,5403.18,3382.06,3382.06,2596.82,785.24,0.0,0.0,0.0,Feb-2017,261.08,Mar-2017,Feb-2017,0,61.0,1,INDIVIDUAL,NaN,NaN,NaN,0,0,148154,2.0,2.0,0.0,1.0,13.0,136887.0,86.0,4.0,6.0,1984.0,49.0,31400,2.0,2.0,0.0,7,5926,1188.0,79.5,0,0,147.0,215,4,4,2,13.0,NaN,13.0,34.0,1,3,11,3,6,21,25,45.0,12,27,0.0,0,0,4,97.1,100.0,0,0,168819,148154,5800,136996
2,68536799,73426617,10000,10000,10000.0,36 months,10.78%,326.35,B,B4,Lpn,3 years,MORTGAGE,41600.0,Not Verified,Dec-2015,Current,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,472xx,IN,15.78,0,Oct-2004,0,NaN,NaN,18,0,12958,52.5%,33,w,6753.97,6753.97,4227.58,4227.58,3246.03,981.55,0.0,0.0,0.0,Feb-2017,326.35,Mar-2017,Feb-2017,0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0,0,168304,2.0,9.0,2.0,3.0,2.0,27723.0,94.0,0.0,2.0,4958.0,75.0,24700,2.0,4.0,2.0,5,9350,4617.0,66.8,0,0,134.0,124,16,2,2,16.0,NaN,7.0,NaN,0,2,5,3,4,16,8,15.0,5,18,0.0,0,0,2,100.0,33.3,0,0,190694,40681,13900,29512
3,68355089,73244858,24700,24700,24700.0,36 months,11.99%,820.28,C,C1,Engineer,10+ years,MORTGAGE,65000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,small_business,Business,577xx,SD,16.06,1,Dec-1999,4,6.0,NaN,22,0,21470,19.2%,38,w,0.00,0.00,25679.66,25679.66,24700.00,979.66,0.0,0.0,0.0,Jun-2016,926.35,NaN,Jan-2017,0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0,0,204396,1.0,1.0,0.0,1.0,19.0,18005.0,73.0,2.0,3.0,6472.0,29.0,111800,0.0,0.0,6.0,4,9733,57830.0,27.1,0,0,113.0,192,2,2,4,2.0,NaN,0.0,6.0,0,5,5,13,17,6,20,27.0,5,22,0.0,0,0,2,97.4,7.7,0,0,314017,39475,79300,24667
4,68506885,73396712,10000,10000,10000.0,60 months,11.99%,222.40,C,C1,CARDIOVASCULAR TECH,10+ years,RENT,42500.0,Not Verified,Dec-2015,Current,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,460xx,IN,31.04,0,Dec-1998,1,NaN,NaN,10,0,5812,40.9%,23,w,8308.67,8308.67,2874.55,2874.55,1691.33,1183.22,0.0,0.0,0.0,Feb-2017,222.40,Mar-2017,Feb-2017,0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0,0,41166,1.0,3.0,0.0,2.0,13.0,35354.0,76.0,1.0,1.0,3118.0,67.0,14200,1.0,1.0,1.0,3,4117,7288.0,44.4,0,0,129.0,204,5,5,0,5.0,NaN,5.0,NaN,0,4,4,6,9,12,7,11.0,4,10,0.0,0,0,1,100.0,50.0,0,0,61054,41166,13100,46854

In [8]:
df.shape

(421095, 111)

In [18]:
len(df['url'].unique())

421095

In [21]:
df[df['loan_amnt']<> df['funded_amnt']]

Empty DataFrame
Columns: [id, member_id, loan_amnt, funded_amnt, funded_amnt_inv, term, int_rate, installment, grade, sub_grade, emp_title, emp_length, home_ownership, annual_inc, verification_status, issue_d, loan_status, pymnt_plan, url, desc, purpose, title, zip_code, addr_state, dti, delinq_2yrs, earliest_cr_line, inq_last_6mths, mths_since_last_delinq, mths_since_last_record, open_acc, pub_rec, revol_bal, revol_util, total_acc, initial_list_status, out_prncp, out_prncp_inv, total_pymnt, total_pymnt_inv, total_rec_prncp, total_rec_int, total_rec_late_fee, recoveries, collection_recovery_fee, last_pymnt_d, last_pymnt_amnt, next_pymnt_d, last_credit_pull_d, collections_12_mths_ex_med, mths_since_last_major_derog, policy_code, application_type, annual_inc_joint, dti_joint, verification_status_joint, acc_now_delinq, tot_coll_amt, tot_cur_bal, open_acc_6m, open_il_6m, open_il_12m, open_il_24m, mths_since_rcnt_il, total_bal_il, il_util, open_rv_12m, open_rv_24m, max_bal_bc, all_util, total_rev_hi_lim, inq_fi, total_cu_tl, inq_last_12m, acc_open_past_24mths, avg_cur_bal, bc_open_to_buy, bc_util, chargeoff_within_12_mths, delinq_amnt, mo_sin_old_il_acct, mo_sin_old_rev_tl_op, mo_sin_rcnt_rev_tl_op, mo_sin_rcnt_tl, mort_acc, mths_since_recent_bc, mths_since_recent_bc_dlq, mths_since_recent_inq, mths_since_recent_revol_delinq, num_accts_ever_120_pd, num_actv_bc_tl, num_actv_rev_tl, num_bc_sats, num_bc_tl, num_il_tl, num_op_rev_tl, num_rev_accts, num_rev_tl_bal_gt_0, num_sats, num_tl_120dpd_2m, ...]
Index: []

#### All of the loans in the dataset are unique and issued. 
https://help.lendingclub.com/hc/en-us/articles/215488038-What-do-the-different-Note-statuses-mean-

In [44]:
pd.Series(df['loan_status']).value_counts()

Current               277527
Fully Paid             94968
Charged Off            33416
Late (31-120 days)      8626
In Grace Period         4674
Late (16-30 days)       1624
Default                  260
Name: loan_status, dtype: int64

In [16]:
df.describe()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,total_acc,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_amnt,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,annual_inc_joint,dti_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
count,4.210950e+05,4.210950e+05,421095.000000,421095.000000,421095.000000,421095.000000,4.210950e+05,421095.000000,421095.000000,421095.000000,217133.000000,74415.000000,421095.000000,421095.000000,4.210950e+05,421095.000000,421095.000000,421095.000000,421095.000000,421095.000000,421095.000000,421095.000000,421095.000000,421095.000000,421095.000000,421095.000000,421095.000000,122729.000000,421095.0,511.000000,509.000000,421095.000000,421095.000000,4.210950e+05,21372.000000,21372.000000,21372.000000,21372.000000,20810.000000,21372.000000,18617.000000,21372.000000,21372.000000,21372.000000,21372.000000,4.210950e+05,21372.000000,21372.000000,21372.000000,421095.00000,421095.000000,417132.000000,416868.000000,421095.000000,421095.000000,408841.000000,421095.000000,421095.000000,421095.000000,421095.000000,417297.000000,108600.000000,376496.000000,151737.000000,421095.000000,421095.000000,421095.000000,421095.000000,421095.000000,421095.000000,421095.000000,421094.000000,421095.000000,421095.000000,401865.000000,421095.000000,421095.000000,421095.000000,421095.000000,416856.000000,421095.000000,421095.000000,4.210950e+05,4.210950e+05,421095.000000,4.210950e+05
mean,5.393097e+07,5.759576e+07,15240.285862,15240.285862,15234.156412,441.859660,7.696561e+04,19.195989,0.347397,0.572690,34.023391,66.592609,11.948643,0.233776,1.768548e+04,25.493468,6731.852248,6728.957444,9724.272952,9720.600967,7468.877666,2193.412444,0.573743,61.409098,10.793400,2771.671503,0.020240,45.114741,1.0,109981.011585,18.310118,0.006087,257.478241,1.400755e+05,1.109021,2.928832,0.761651,1.674574,20.912686,36552.811389,71.580491,1.389060,2.975482,5887.979740,60.881995,3.365771e+04,0.943945,1.537058,2.234091,4.66500,13104.784721,9636.063992,62.228136,0.010420,13.765184,127.567419,186.586697,13.451247,8.013204,1.685261,24.856534,39.838177,6.751163,35.797142,0.527054,3.740966,5.860832,4.799879,8.137138,8.649001,8.431786,14.883601,5.809238,11.894537,0.000761,0.004042,0.094318,2.170947,93.924313,47.527110,0.133188,0.064556,1.734070e+05,5.222199e+04,21958.208958,4.347865e+04
std,9.475423e+06,1.013358e+07,8571.325901,8571.325901,8567.935752,244.850838,7.394996e+04,23.504038,0.927695,0.867776,21.990270,25.577899,5.633119,0.649778,2.419503e+04,12.097200,6975.864148,6972.541062,7161.590912,7159.162377,6523.441530,1900.836729,5.317043,461.711020,81.024136,5741.807514,0.157506,22.537808,0.0,52730.379847,7.169233,0.086482,2240.648162,1.552696e+05,1.242675,3.089987,0.996035,1.688725,27.209081,43103.833619,23.021964,1.520129,2.631886,5284.701239,20.013842,3.766404e+04,1.446872,2.723339,2.480242,3.19538,15671.803897,14774.166134,27.576378,0.117019,781.821107,52.075471,95.374931,17.156985,9.189312,1.990160,32.272793,23.003885,5.914006,22.628516,1.332797,2.304542,3.439764,3.036184,4.822698,7.471041,4.664381,8.289379,3.346698,5.615119,0.030169,0.067965,0.522758,1.853858,8.875399,36.054458,0.385975,0.444231,1.756722e+05,4.907494e+04,21840.371112,4.394271e+04
min,5.670500e+04,7.082500e+04,1000.000000,1000.000000,900.000000,14.010000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000e+00,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,17950.000000,3.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.500000e+03,0.000000e+00,0.000000,0.000000e+00
25%,4.612481e+07,4.922617e+07,8500.000000,8500.000000,8500.000000,263.930000,4.600000e+04,12.590000,0.000000,0.000000,15.000000,50.000000,8.000000,0.000000,6.480000e+03,17.000000,0.000000,0.000000,4840.675000,4839.190000,3194.125000,838.820000,0.000000,0.000000,0.000000,299.150000,0.000000,27.000000,1.0,76032.500000,13.200000,0.000000,0.000000,3.103900e+04,0.000000,1.000000,0.000000,0.000000,6.000000,10251.500000,59.000000,0.000000,1.000000,2411.000000,48.000000,1.440000e+04,0.000000,0.000000,0.000000,2.00000,3199.000000,1345.000000,41.500000,0.000000,0.000000,101.000000,120.000000,4.000000,3.000000,0.000000,6.000000,20.000000,2.000000,17.000000,0.000000,2.000000,3.000000,3.000000,5.000000,4.000000,5.000000,9.000000,3.000000,8.000000,0.000000,0.000000,0.000000,1.000000,90.900000,15.400000,0.000000,0.000000,5.090900e+04,2.259850e+04,7800.000000,1.548150e+04
50%,5.536031e+07,5.895358e+07,14000.000000,14000.000000,14000.000000,385.410000,6.500000e+04,18.600000,0.000000,0.000000,31.000000,67.000000,11.000000,0.000000,1.199600e+04,24.000000,4870.950000,4869.290000,7753.457826,7749.700000,5333.620000,1626.890000,0.000000,0.000000,0.000000,483.520000,0.000000,45.000000,1.0,101771.000000,17.610000,0.000000,0.000000,7.972900e+04,1.000000,2.000000,0.000000,1.000000,12.000000,24684.500000,75.000000,1.000000,2.000000,4483.000000,62.000000,2.460000e+04,0.000000,0.000000,2.000000,4.00000,7262.000000,4366.000000,65.800000,0.000000,0.000000,130.000000,170.000000,8.000000,5.000000,1.000000,14.000000,38.000000,5.000000,33.000000,0.000000,3.000000,5.000000,4.000000,7.000000,7.000000,8.000000,13.000000,5.000000,11.000000,0.000000,0.000000,0.000000,2.000000,97.400000,50.000000,0.000000,0.000000,1.114050e+05,3.959600e+04,15200.000000,3.297000e+04
75%,6.186217e+07,6.604584e+07,20000.000000,20000.000000,20000.000000,578.790000,9.169050e+04,25.340000,0.000000,1.000000,50.000000,82.000000,15.000000,0.000000,2.142800e+04,32.000000,10977.690000,10972.690000,12453.750000,12448.320000,9515.440000,2962.305000,0.000000,0.000000,0.000000,923.730000,0.000000,63.000000,1.0,132800.000000,22.650000,0.000000,0.000000,2.074750e+05,2.000000,4.000000,1.000000,2.000000,23.000000,47858.000000,88.000000,2.000000,4.000000,7771.500000,75.000000,4.168850e+04,1.000000,2.000000,3.000000,6.00000,17974.500000,11574.000000,86.500000,0.000000,0.000000,153.000000,237.000000,16.000000,10.000000,3.000000,29.000000,60.000000,10.000000,53.000000,0.000000,5.000000,7.000000,6.000000,11.000000,11.000000,11.000000,19.000000,7.000000,15.000000,0.000000,0.000000,0.000000,3.000000,100.000000,75.000000,0.000000,0.000000,2.496290e+05,6.565100e+04,28600.000000,5.829900e+04
max,6.861706e+07,7.354484e+07,35000.000000,35000.000000,35000.000000,1445.460000,9.500000e+06,9999.000000,39.000000,6.000000,176.000000,120.000000,90.000000,86.000000,2.904836e+06,169.000000,40884.740000,40884.740000,50312.207800,50312.210000,35000.000000,16715.940000,324.750000,33666.340000,6059.941200,36475.590000,14.000000,176.000000,1.0,500000.000000,43.860000,14.000000,496651.000000,4.447397e+06,14.000000,40.000000,12.000000,19.000000,363.000000,878459.000000,223.000000,22.000000,43.000000,127305.000000,151.000000,9.999999e+06,17.000000,35.000000,32.000000,64.00000,555925.000000,559912.000000,318.200000,10.000000,159177.000000,724.000000,851.000000,324.000000,263.000000,52.000000,615.000000,195.000000,25.000000,176.000000,39.000000,32.000000,52.000000,63.000000,70.000000,132.000000,83.000000,118.000000,45.000000,90.000000,6.000000,4.000000,39.000000,30.000000,100.000000,100.000000,11.000000,85.000000,9.999999e+06,2.921551e+06,834300.000000,2.101913e+06

In [19]:
print_full(df.dtypes)

id                                  int64
member_id                           int64
loan_amnt                           int64
funded_amnt                         int64
funded_amnt_inv                   float64
term                               object
int_rate                           object
installment                       float64
grade                              object
sub_grade                          object
emp_title                          object
emp_length                         object
home_ownership                     object
annual_inc                        float64
verification_status                object
issue_d                            object
loan_status                        object
pymnt_plan                         object
url                                object
desc                               object
purpose                            object
title                              object
zip_code                           object
addr_state                         object
dti                               float64
delinq_2yrs                         int64
earliest_cr_line                   object
inq_last_6mths                      int64
mths_since_last_delinq            float64
mths_since_last_record            float64
open_acc                            int64
pub_rec                             int64
revol_bal                           int64
revol_util                         object
total_acc                           int64
initial_list_status                object
out_prncp                         float64
out_prncp_inv                     float64
total_pymnt                       float64
total_pymnt_inv                   float64
total_rec_prncp                   float64
total_rec_int                     float64
total_rec_late_fee                float64
recoveries                        float64
collection_recovery_fee           float64
last_pymnt_d                       object
last_pymnt_amnt                   float64
next_pymnt_d                       object
last_credit_pull_d                 object
collections_12_mths_ex_med          int64
mths_since_last_major_derog       float64
policy_code                         int64
application_type                   object
annual_inc_joint                  float64
dti_joint                         float64
verification_status_joint          object
acc_now_delinq                      int64
tot_coll_amt                        int64
tot_cur_bal                         int64
open_acc_6m                       float64
open_il_6m                        float64
open_il_12m                       float64
open_il_24m                       float64
mths_since_rcnt_il                float64
total_bal_il                      float64
il_util                           float64
open_rv_12m                       float64
open_rv_24m                       float64
max_bal_bc                        float64
all_util                          float64
total_rev_hi_lim                    int64
inq_fi                            float64
total_cu_tl                       float64
inq_last_12m                      float64
acc_open_past_24mths                int64
avg_cur_bal                         int64
bc_open_to_buy                    float64
bc_util                           float64
chargeoff_within_12_mths            int64
delinq_amnt                         int64
mo_sin_old_il_acct                float64
mo_sin_old_rev_tl_op                int64
mo_sin_rcnt_rev_tl_op               int64
mo_sin_rcnt_tl                      int64
mort_acc                            int64
mths_since_recent_bc              float64
mths_since_recent_bc_dlq          float64
mths_since_recent_inq             float64
mths_since_recent_revol_delinq    float64
num_accts_ever_120_pd               int64
num_actv_bc_tl                      int64
num_actv_rev_tl                     int64
num_bc_sats                         int64
num_bc_tl                           int64
num_il_tl                           int64
num_op_rev_tl                       int64
num_rev_accts                     float64
num_rev_tl_bal_gt_0                 int64
num_sats                            int64
num_tl_120dpd_2m                  float64
num_tl_30dpd                        int64
num_tl_90g_dpd_24m                  int64
num_tl_op_past_12m                  int64
pct_tl_nvr_dlq                    float64
percent_bc_gt_75                  float64
pub_rec_bankruptcies                int64
tax_liens                           int64
tot_hi_cred_lim                     int64
total_bal_ex_mort                   int64
total_bc_limit                      int64
total_il_high_credit_limit          int64
dtype: object

In [25]:
pd.Series(df['loan_status']).value_counts()

Current               277527
Fully Paid             94968
Charged Off            33416
Late (31-120 days)      8626
In Grace Period         4674
Late (16-30 days)       1624
Default                  260
Name: loan_status, dtype: int64

In [43]:
df[(df['loan_status']=='Charged Off') & (df['collection_recovery_fee']<df['recoveries'])].count()

id                                12643
member_id                         12643
loan_amnt                         12643
funded_amnt                       12643
funded_amnt_inv                   12643
term                              12643
int_rate                          12643
installment                       12643
grade                             12643
sub_grade                         12643
emp_title                         11865
emp_length                        12643
home_ownership                    12643
annual_inc                        12643
verification_status               12643
issue_d                           12643
loan_status                       12643
pymnt_plan                        12643
url                               12643
desc                                  0
purpose                           12643
title                             12641
zip_code                          12643
addr_state                        12643
dti                               12643
delinq_2yrs                       12643
earliest_cr_line                  12643
inq_last_6mths                    12643
mths_since_last_delinq             6692
mths_since_last_record             2629
open_acc                          12643
pub_rec                           12643
revol_bal                         12643
revol_util                        12637
total_acc                         12643
initial_list_status               12643
out_prncp                         12643
out_prncp_inv                     12643
total_pymnt                       12643
total_pymnt_inv                   12643
total_rec_prncp                   12643
total_rec_int                     12643
total_rec_late_fee                12643
recoveries                        12643
collection_recovery_fee           12643
last_pymnt_d                      12459
last_pymnt_amnt                   12643
next_pymnt_d                          0
last_credit_pull_d                12643
collections_12_mths_ex_med        12643
                                  ...
open_il_12m                         242
open_il_24m                         242
mths_since_rcnt_il                  235
total_bal_il                        242
il_util                             218
open_rv_12m                         242
open_rv_24m                         242
max_bal_bc                          242
all_util                            242
total_rev_hi_lim                  12643
inq_fi                              242
total_cu_tl                         242
inq_last_12m                        242
acc_open_past_24mths              12643
avg_cur_bal                       12643
bc_open_to_buy                    12470
bc_util                           12461
chargeoff_within_12_mths          12643
delinq_amnt                       12643
mo_sin_old_il_acct                12328
mo_sin_old_rev_tl_op              12643
mo_sin_rcnt_rev_tl_op             12643
mo_sin_rcnt_tl                    12643
mort_acc                          12643
mths_since_recent_bc              12471
mths_since_recent_bc_dlq           3522
mths_since_recent_inq             11897
mths_since_recent_revol_delinq     4710
num_accts_ever_120_pd             12643
num_actv_bc_tl                    12643
num_actv_rev_tl                   12643
num_bc_sats                       12643
num_bc_tl                         12643
num_il_tl                         12643
num_op_rev_tl                     12643
num_rev_accts                     12643
num_rev_tl_bal_gt_0               12643
num_sats                          12643
num_tl_120dpd_2m                  12017
num_tl_30dpd                      12643
num_tl_90g_dpd_24m                12643
num_tl_op_past_12m                12643
pct_tl_nvr_dlq                    12643
percent_bc_gt_75                  12458
pub_rec_bankruptcies              12643
tax_liens                         12643
tot_hi_cred_lim                   12643
total_bal_ex_mort                 12643
total_bc_limit                    12643
total_il_high_credit_limit        12643
dtype: int64

In [4]:
pd.Series(df['issue_d']).value_counts()

Oct-2015    48631
Jul-2015    45962
Dec-2015    44343
Nov-2015    37530
Aug-2015    35886
Apr-2015    35427
Jan-2015    35107
May-2015    31913
Sep-2015    28641
Jun-2015    28485
Mar-2015    25400
Feb-2015    23770
Name: issue_d, dtype: int64

In [7]:
df[df['member_id']==73517949]

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
0,68615169,73517949,16000,16000,16000.0,60 months,8.49%,328.19,B,B1,Supervisor,5 years,MORTGAGE,62000.0,Source Verified,Dec-2015,Current,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,credit_card,Credit card refinancing,936xx,CA,28.92,0,Mar-2002,0,39.0,NaN,10,0,15763,51.2%,24,w,13083.35,13083.35,4247.6,4247.6,2916.65,1330.95,0.0,0.0,0.0,Feb-2017,328.19,Mar-2017,Feb-2017,0,61.0,1,INDIVIDUAL,NaN,NaN,NaN,0,0,227708,3.0,3.0,1.0,2.0,3.0,48608.0,82.0,2.0,4.0,4727.0,71.0,30800,1.0,1.0,0.0,6,22771,8703.0,63.0,0,0,165.0,159,3,3,3,3.0,NaN,17.0,39.0,1,4,5,4,7,9,6,12.0,6,10,0.0,0,0,3,87.5,50.0,0,0,307343,64371,23500,59526

In [14]:
df_test = pd.read_csv(data_loc +'\\'+ 'LoanStats_2017Q1.csv')

C:\Users\Chao Cheng\Anaconda2\lib\site-packages\IPython\core\interactiveshell.py:2717: DtypeWarning: Columns (0,1,2,3,4,7,13,18,19,24,25,27,28,29,30,31,32,34,36,37,38,39,40,41,42,43,44,46,49,50,51,53,54,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [16]:
df_test.shape

(96782, 1)

In [17]:
df_test.head()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Notes offered by Prospectus (https://www.lendingclub.com/info/prospectus.action)
id  member_id loan_amnt funded_amnt funded_amnt_inv term       int_rate installment grade sub_grade emp_title                 emp_length home_ownership annual_inc verification_status issue_d  loan_status pymnt_plan url desc purpose        title          zip_code addr_state dti   delinq_2yrs earliest_cr_line inq_last_6mths mths_since_last_delinq mths_since_last_record open_acc pub_rec revol_bal revol_util total_acc initial_list_status out_prncp out_prncp_inv total_pymnt total_pymnt_inv total_rec_prncp total_rec_int total_rec_late_fee recoveries collection_recovery_fee last_pymnt_d last_pymnt_amnt next_pymnt_d last_credit_pull_d collections_12_mths_ex_med mths_since_last_major_derog policy_code application_type annual_inc_joint dti_joint verification_status_joint acc_now_delinq tot_coll_amt tot_cur_bal open_acc_6m open_il_6m open_il_12m open_il_24m mths_since_rcnt_il total_bal_il il_util open_rv_12m open_rv_24m max_bal_bc all_util total_rev_hi_lim inq_fi total_cu_tl inq_last_12m acc_open_past_24mths avg_cur_bal bc_open_to_buy bc_util chargeoff_within_12_mths delinq_amnt mo_sin_old_il_acct mo_sin_old_rev_tl_op mo_sin_rcnt_rev_tl_op mo_sin_rcnt_tl mort_acc mths_since_recent_bc mths_since_recent_bc_dlq mths_since_recent_inq mths_since_recent_revol_delinq num_accts_ever_120_pd num_actv_bc_tl num_actv_rev_tl num_bc_sats num_bc_tl num_il_tl num_op_rev_tl num_rev_accts num_rev_tl_bal_gt_0 num_sats num_tl_120dpd_2m num_tl_30dpd num_tl_90g_dpd_24m num_tl_op_past_12m pct_tl_nvr_dlq percent_bc_gt_75 pub_rec_bankruptcies tax_liens tot_hi_cred_lim total_bal_ex_mort total_bc_limit total_il_high_credit_limit revol_bal_joint sec_app_earliest_cr_line sec_app_inq_last_6mths sec_app_mort_acc sec_app_open_acc sec_app_revol_util sec_app_open_il_6m sec_app_num_rev_accts sec_app_chargeoff_within_12_mths sec_app_collections_12_mths_ex_med                sec_app_mths_since_last_major_derog
NaN NaN       3600      3600        3600             36 months   7.49%  111.97      A     A4        Code/Compliance Inspector 10+ years  MORTGAGE       120000     Not Verified        Mar-2017 Issued      n          NaN NaN  other          Other          467xx    IN         18.9  0           Aug-1992         1              NaN                    96                     18       1       5658      14.9%      33        w                   3600.00   3600.00       0.0         0.00            0.00            0.00          0.0                0.0        0.0                     NaN          0.0             Apr-2017     Apr-2017           0                          NaN                         1           INDIVIDUAL       NaN              NaN       NaN                       0              0            36506       2           6          2           6           2                  30848        55      4           7           1020       39       37900            3      1           4            13                   2147        7980           11.3    0                        0           166                295                  3                     2              0        9                    NaN                      2                     NaN                            0                     1              4               2           3         17        12            16            4                   18       0                0            0                  6                  100            0                1                    0         93599           36506             9000           55699                      NaN             NaN                      NaN                    NaN              NaN              NaN                NaN                NaN                   NaN                              NaN                                                                               NaN
              15000     15000       15000            60 months  14.99%  356.78      C     C4        Senior Superintendent     10+ years  MORTGAGE       125000     Not Verified        Mar-2017 Issued      n          NaN NaN  other          Other          064xx    CT         17.25 0           Sep-1989         0              NaN                    NaN                    11       0       53167     75.3%      18        w                   15000.00  15000.00      0.0         0.00            0.00            0.00          0.0                0.0        0.0                     NaN          0.0             Apr-2017     Apr-2017           0                          NaN                         1           INDIVIDUAL       NaN              NaN       NaN                       0              0            90423       0           2          0           1           22                 16197        54      0           3           15199      69       70600            1      0           0            4                    8220        13968          76.8    0                        0           158                245                  16                    16             2        16                   NaN                      16                    NaN                            0                     5              7               6           8         6         8             10            7                   11       0                0            0                  0                  100            66.7             0                    0         148572          69364             60300          30224                      NaN             NaN                      NaN                    NaN              NaN              NaN                NaN                NaN                   NaN                              NaN                                                                               NaN
              8400      8400        8400             36 months  11.39%  276.56      B     B3        IT Tech                   8 years    MORTGAGE       50000      Source Verified     Mar-2017 Issued      n          NaN NaN  other          Other          454xx    OH         15.63 0           Apr-2005         0              NaN                    NaN                    14       0       12831     30.3%      30        w                   8400.00   8400.00       0.0         0.00            0.00            0.00          0.0                0.0        0.0                     NaN          0.0             Apr-2017     Apr-2017           0                          NaN                         1           INDIVIDUAL       NaN              NaN       NaN                       0              271          161061      3           2          1           2           10                 38760        105     4           8           5338       65       42300            4      1           7            10                   12389       24145          33.1    0                        0           131                143                  4                     4              4        4                    NaN                      10                    NaN                            0                     4              5               7           11        9         11            16            5                   14       0                0            0                  5                  100            14.3             0                    0         205671          51591             36100          36876                      NaN             NaN                      NaN                    NaN              NaN              NaN                NaN                NaN                   NaN                              NaN                                                                               NaN
              4000      4000        4000             36 months  10.49%  130         B     B2        Dental hygienist          2 years    RENT           50000      Source Verified     Mar-2017 Issued      n          NaN NaN  major_purchase Major purchase 768xx    TX         33.61 1           Apr-2003         0              6                      37                     10       1       4388      33.2%      33        w                   4000.00   4000.00       0.0         0.00            0.00            0.00          0.0                0.0        0.0                     NaN          0.0             Apr-2017     Apr-2017           0                          67                          1           INDIVIDUAL       NaN              NaN       NaN                       0              0            136208      0           4          1           2           7                  131820       70      0           4           2461       56       13200            0      0           1            6                    13621       39             98.4    0                        0           148                163                  15                    7              6        120                  NaN                      9                     61                             1                     1              4               1           3         15        6             12            4                   10       0                0            0                  1                  87.5           100              0                    0         152852          136208            2500           139652                     NaN             NaN                      NaN                    NaN              NaN              NaN                NaN                NaN                   NaN                              NaN                                                                               NaN